### PR TITLE
Updates for RabbitMQ 3.0.1 and Erlang R15.3.1

### PR DESCRIPTION
**Pull request by kmsheehan**

### CODE REVIEW

**Comment by smerchek** [comment]
I did have a couple issues using these (although I can't quite tell why). Erlang seemed to work fine.

With RabbitMQ, initially it failed because 2.7.3 was already installed. After uninstalling, 3.0.1 installed fine but then threw exceptions when trying to run the .bat file.

```
Elevating Permissions and running C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& import-module -name  'C:\NuGet\chocolateyInstall\helpers\chocolateyInstaller.psm1'; try{C:\Chocolatey\lib\rabbitmq.3.0.1\tools\SetupRabbitMqManagement.bat; start-sleep 6;}catch{write-error 'That was not sucessful';start-sleep 8;throw;}". This may take awhile, depending on the statements.
Write-Error : [ERROR] Running C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe with C:\Chocolatey\lib\rabbitmq.3.0.
1\tools\SetupRabbitMqManagement.bat; was not successful.
At C:\NuGet\chocolateyInstall\helpers\chocolateyinstaller.psm1:30 char:14
+         Write-Error <<<<  $errorMessage
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

Write-Error : Could not rename 'C:\Users\SCOTT~1.SME\AppData\Local\Temp\chocolatey\RabbitMQ\success.log' to 'C:\Users\SCOTT~
1.SME\AppData\Local\Temp\chocolatey\RabbitMQ\success.log.old': Exception calling "Move" with "2" argument(s): "The process c
annot access the file because it is being used by another process."
At C:\NuGet\chocolateyInstall\helpers\chocolateyinstaller.psm1:370 char:16
+     Write-Error <<<<  "Could not rename `'$successLog`' to `'$($successLog).old`': $($_.Exception.Message)"
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

Write-Error : RabbitMQ did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] [ERROR] Running C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe with C:\Chocolatey\lib\rabbitmq.3.0.1\tool
s\SetupRabbitMqManagement.bat; was not successful.
-----------------------
At C:\NuGet\chocolateyInstall\helpers\chocolateyinstaller.psm1:381 char:13
+     Write-Error <<<<  $errorMessage
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

[ERROR] Running C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe with C:\Chocolatey\lib\rabbitmq.3.0.1\tools\SetupR
abbitMqManagement.bat; was not successful.
At C:\NuGet\chocolateyInstall\helpers\chocolateyinstaller.psm1:31 char:8
+         throw <<<<  $errorMessage
    + CategoryInfo          : OperationStopped: ([ERROR] Running...not successful.:String) [], RuntimeException
    + FullyQualifiedErrorId : [ERROR] Running C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe with C:\Chocolatey\
   lib\rabbitmq.3.0.1\tools\SetupRabbitMqManagement.bat; was not successful.
```

Have any idea what might be causing this?

**Comment by smerchek** [comment]
In addition, there might be partially just a problem with my set up. If I try to run the following, I get an error anyway.

`>cmd /c "c:\Program Files (x86)\RabbitMQ Server\rabbitmq_server-3.0.1\sbin\rabbitmq-plugins.bat" enable rabbitmq_management`

```
{error_logger,{{2013,1,28},{13,34,59}},"Failed to create cookie file 'u:/.erlang
.cookie': enoent",[]}
{error_logger,{{2013,1,28},{13,34,59}},crash_report,[[{initial_call,{auth,init,[
'Argument__1']}},{pid,<0.18.0>},{registered_name,[]},{error_info,{exit,{"Failed
to create cookie file 'u:/.erlang.cookie': enoent",[{auth,init_cookie,0,[{file,"
auth.erl"},{line,285}]},{auth,init,1,[{file,"auth.erl"},{line,139}]},{gen_server
,init_it,6,[{file,"gen_server.erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{f
ile,"proc_lib.erl"},{line,227}]}]},[{gen_server,init_it,6,[{file,"gen_server.erl
"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]
}},{ancestors,[net_sup,kernel_sup,<0.9.0>]},{messages,[]},{links,[<0.16.0>]},{di
ctionary,[]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,24},{
reductions,841}],[]]}
{error_logger,{{2013,1,28},{13,35,0}},supervisor_report,[{supervisor,{local,net_
sup}},{errorContext,start_error},{reason,{"Failed to create cookie file 'u:/.erl
ang.cookie': enoent",[{auth,init_cookie,0,[{file,"auth.erl"},{line,285}]},{auth,
init,1,[{file,"auth.erl"},{line,139}]},{gen_server,init_it,6,[{file,"gen_server.
erl"},{line,304}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}
]}]}},{offender,[{pid,undefined},{name,auth},{mfargs,{auth,start_link,[]}},{rest
art_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2013,1,28},{13,35,0}},supervisor_report,[{supervisor,{local,kern
el_sup}},{errorContext,start_error},{reason,shutdown},{offender,[{pid,undefined}
,{name,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanen
t},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2013,1,28},{13,35,0}},std_info,[{application,kernel},{exited,{sh
utdown,{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kern
el,{shutdown,{kernel,start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kerne
l,{shutdown,{kernel,start,[normal,[]]}}})
```

**Comment by kmsheehan** [comment]
What happens is this - The log file was somehow still in use. 'C:\Users\SCOTT~1.SME\AppData\Local\Temp\chocolatey\RabbitMQ\success.log' I saw that once or twice.  You could log out and log in to make sure something from the uninstall is holding the file.  

 C:\Users\SCOTT~1.SME\AppData\Local\Temp\chocolatey\RabbitMQ is where the installer is placed and the log is written.

If this script is an issue I can either remove it from execution during the install and provide it for the user to run or simply remove it entirely.

Another way to 'correct' this or run it from a clean environment is:
1. manually uninstall RabbitMQ
2. manually uninstall Erlang
3. Delete (if it exists) c:\Chocolatey\lib\RabbitMQxxxx\
4. Delete (if it exists) C:\Users\SCOTT~1.SME\AppData\Local\Temp\chocolatey\RabbitMQ
5. Delete if you don't have any settings you want to carry over (if it exists) C:\Users\SCOTT~1.SME\AppData\Local\Temp\chocolatey\RabbitMQ

Kevin

**Comment by smerchek** [comment]
I think I'm just going to verify this from a clean VM. Other than these errors I've run into with my setup, I think this looks fine. So, thank you.

**Comment by smerchek** [comment]
Ok, the fresh VM worked better so far. However, I get the following error when running the .bat.

```
******************************
ERLANG_HOME not set correctly.
******************************

Please either set ERLANG_HOME to point to your Erlang installation or place the
RabbitMQ server distribution in the Erlang lib folder.
```

EDIT: It appears that this is because I ran the tools (and the Rabbit install) without restarting my prompt.

**Comment by smerchek** [comment]
Ok, I'm happy. Thanks for your help Kevin!

**Comment by kmsheehan** [comment]
That error

---

ERLANG_HOME not set correctly.

---

seems to occur during the Erlang setup where the C:\Program Files\erl5.9.3.1\bin is not readable.  I got that once and had to clean up Erlang and reboot so it would install correctly.  The RabbitMQ installer looks in that Directory for the erl.exe and if it finds it then i sets up the environment variable - if it doesn't it just seems to abort that variable set and complains that it isn't set.

**Pull request merged**
